version: "3.4"

services:
  nginx:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf